### ISSUE TITLE
Inserción de datos en las tablas de MySQL

### ISSUE THREAD

**Issue by JaquiM2004** [DanaContreras17/ProyectoFinal951-2024-2#11]
Insertar los datos en las tablas correspondientes de MySQL, documentar el proceso de inserción y verificar que todos los datos se insertan correctamente.

Checklist para Inserción de Datos en las Tablas de MySQL

- [x] Cargar el archivo `datasets/libros_limpios.csv` en un DataFrame utilizando `pandas`.
- [x] Escribir el código para insertar los datos en las tablas correspondientes de MySQL.
- [x] Ejecutar el script de inserción y verificar que todos los datos se insertan correctamente sin errores.
- [x] Realizar consultas de verificación para confirmar que los datos están en las tablas correctamente.

**Comment by Leosaucedo22** [comment]
La insercion en las tablas de la base de datos funciono sin ningun problema
