### ISSUE TITLE
Dashboard 3 - Tendencias en Publicaciones y Popularidad por Formato

### ISSUE THREAD

**Issue by JaquiM2004** [DanaContreras17/ProyectoFinal951-2024-2#15]
Desarrollar un dashboard que muestre tendencias en la cantidad de publicaciones y popularidad de formatos de libros.

Checklist para Dashboard 3 - Tendencias en Publicaciones y Popularidad por Formato

- [x] Cargar los datos necesarios desde la base de datos en un DataFrame.
- [x] Crear Dashboard de Comparativa de Formatos de Libros
- [x] Crear Dashboard de Análisis de Autores Populares
- [x] Crear visualizaciones claras para mostrar las tendencias usando dash_bootstrap_components, plotly.express, css.
- [x] Agregar etiquetas, leyendas y títulos descriptivos para mejorar la comprensión de los gráficos.
- [x] Guardar el script del dashboard en la carpeta `Dashboard`.

**Comment by medranopsycho** [comment]
Se realizo el dashboard 3 trabajado en conjunto con mi compañera Yuliana correctamente.
