### ISSUE TITLE
Crear el codigo de la base de datos en MySql

### ISSUE THREAD

**Issue by Leosaucedo22** [DanaContreras17/ProyectoFinal951-2024-2#16]
Diseñar y crear la base de datos en MySQL basada en los datos limpios de libros. Esto incluye definir la estructura de las tablas y relaciones necesarias, y desarrollar el script SQL para crear la base de datos y las tablas.

- [x] Diseñar la estructura de la base de datos, definiendo las tablas y sus campos.
- [x] Especificar las claves primarias y foráneas necesarias para establecer relaciones entre las tablas.
- [x] Escribir el script SQL para crear la base de datos y las tablas en MySQL.
- [x] Verificar que la base de datos y las tablas se crean correctamente en MySQL.
- [x] Documentar la estructura de la base de datos, incluyendo una breve explicación de las tablas y relaciones, en un archivo dentro de `/docs`.
- [x] Subir el script SQL y la documentación al repositorio en las carpetas correspondientes.

**Comment by Yuls18** [comment]
Se completo exitosamente.
