### ISSUE TITLE
Crear el codigo para el menu de inicio de los Dashboards

### ISSUE THREAD

**Issue by Leosaucedo22** [DanaContreras17/ProyectoFinal951-2024-2#17]
Este issue tiene como objetivo crear el código para el menú de inicio de los dashboards, permitiendo la navegación entre los tres dashboards. El menú debe ser claro, fácil de usar y debe enlazar de manera eficiente con las vistas correspondientes.

- [x] Diseñar la estructura del menú de inicio en python.
- [x] Implementar la funcionalidad para enlazar a los tres dashboards.
- [x] Agregar estilo al menú para mejorar la usabilidad (colores, fuentes, etc.).
- [x] Probar la navegación entre los dashboards.
- [x] Documentar el código y las decisiones tomadas en la implementación.

**Comment by DanaContreras17** [comment]
Ya estan enlazados los codigos en el github,

**Comment by DanaContreras17** [comment]
Tarea completada, menu e inicio funcionan correctamente y preparados para agregar las funciones que se tiene que importar para los 3 dashboards.
