### ISSUE TITLE
Creación del Menú de Navegación

### ISSUE THREAD

**Issue by JaquiM2004** [DanaContreras17/ProyectoFinal951-2024-2#18]
Desarrollar un menú de navegación que contenga las siguientes opciones: **Web Scraping**, **Limpieza de Datos**, **Base de Datos** y **Dashboards**. Este menú debe ser accesible desde la página principal y permitir a los usuarios acceder fácilmente a las secciones correspondientes del proyecto.

- [x] Diseñar el layout del menú con un estilo claro y sencillo que incluya las siguientes opciones: 
    - Web Scraping
    - Limpieza de Datos
    - Base de Datos
    - Dashboards
- [x] Implementar el menú utilizando HTML, CSS y/o un framework adecuado (como Dash).
- [x] Asegurarse de que cada opción redirija a la página o sección correspondiente en el proyecto.
- [x] Agregar un diseño coherente con el resto del proyecto (colores, tipografía y estilos).
- [x] Asegurarse de que el menú sea funcional en diferentes dispositivos (responsive).
- [x] Testear que cada opción redirija correctamente a la sección correspondiente (Web Scraping, Limpieza de Datos, Base de Datos, Dashboards).
- [x] Documentar el proceso de creación del menú en el issue.

**Comment by DanaContreras17** [comment]
Para poder realizar el menú hice modificaciones y agregue cosas, como para agregar los archivos csv dentro y fuera de las carpetas de cada proceso, para que también estén los df dentro de la carpeta DataFrames, así como modifique el código de DataCleaning para que estuviera funcionando dentro de una función que la nombre "limpiar_datos" para poder mandarla a llamar en el menú. También modifique unas líneas de código de menu_libros para poder llamar a app, y en el main utilice threading y time para poder correr el Dash, así como también utilice mysql.connector para una condición de insertar primero datos en la base de datos antes de visualizar los dashboards.

**Comment by DanaContreras17** [comment]
Ya quedo listo el menú en el archivo main para todo el proceso del proyecto.
