### ISSUE TITLE
Creación del documento del Proyecto final

### ISSUE THREAD

**Issue by Leosaucedo22** [DanaContreras17/ProyectoFinal951-2024-2#19]
El objetivo de este issue es elaborar un documento en formato Word que contenga toda la información relevante sobre el proyecto. Este documento debe incluir la portada, índice, descripción del problema, objetivos, recolección de datos, transformación, visualización, conclusiones y referencias, con el fin de presentar un resumen completo y detallado del proyecto realizado.

Checklist para la Creación del Documento Final en Word

- [x] Portada: Incluir título, nombres de los integrantes y fecha.
- [x] Índice: Crear indice automático.
- [x] Descripción del Problema: Explicar el contexto y el problema a resolver.
- [x] Objetivos: Plantear las preguntas clave a resolver.
- [x] Recolección de Datos: Describir las fuentes y los datos extraídos.
- [x] Transformación: Incluir diagrama relacional y diccionario de datos.
- [x] Visualización: Describir los dashboards y agregar imágenes.
- [x] Conclusiones: Redactar una conclusión final del proyecto
- [x] Referencias: Incluir enlace al repositorio de GitHub.

**Comment by medranopsycho** [comment]
Ya se creó la estructura final del documento explicando cada uno de los puntos, con esto finalizamos el proyecto!

**Comment by medranopsycho** [comment]
Gracias profe, lo queremos:)
