### ISSUE TITLE
Desarrollo del Script del Web Scraping 

### ISSUE THREAD

**Issue by Leosaucedo22** [DanaContreras17/ProyectoFinal951-2024-2#2]
Crear el script de Web scraping para extraer al menos 300 datos desde el sitio web de libros en este Ghandi.
Objetivo: Extraer campos como título, autor, precio, editorial, formato, etc.

Checklist necesario:

- [x] Acceder al sitio web y analizar la estructura HTML
- [x] Desarrollar el script de scraping para obtener al menos 300 datos
- [x] Extraer los campos requeridos: Título, Autor, Precio, Editorial, Formato

**Comment by DanaContreras17** [comment]
Código completo para el web scraping realizado.
