### ISSUE TITLE
 Guardar datos en CSV

### ISSUE THREAD

**Issue by JaquiM2004** [DanaContreras17/ProyectoFinal951-2024-2#3]
Guardar los datos extraídos en un archive CSV llamado datasets/libros.csv en la carpeta WebScraping.

Checklist para Guardar Datos en CSV

- [x] Exportar los datos extraídos a `datasets/libros.csv` con los campos: título, autor, precio, editorial, y formato.
- [x] Verificar el formato del archivo CSV y el delimitador adecuado.
- [x] Confirmar que todos los registros (mínimo 300) se guarden correctamente.
- [x] Documentar el proceso de creación del archivo CSV en el issue o en `WebScraping`.
- [x] Subir `datasets/libros.csv` al repositorio en `WebScraping`.

**Comment by DanaContreras17** [comment]
Todo el checklist respecto a guardar los datos en .csv completado.
