### ISSUE TITLE
Importar datos para limpieza

### ISSUE THREAD

**Issue by Leosaucedo22** [DanaContreras17/ProyectoFinal951-2024-2#4]
Importar datasets/libros.csv y analizar los datos para entender su estructura y proseguir con el siguiente paso.

- [x] Importar el archivo `libros.csv` usando `pandas`
- [x] Revisar la cantidad total de datos importados
- [x] Analizar la estructura de los datos y los tipos de cada columna

**Comment by medranopsycho** [comment]
Importe el resultado del web scrapping y revise los datos

**Comment by medranopsycho** [comment]
Ya revisado
