### ISSUE TITLE
Limpieza de datos 

### ISSUE THREAD

**Issue by JaquiM2004** [DanaContreras17/ProyectoFinal951-2024-2#5]
Limpiar los datos eliminando duplicados y manejando valores nulos.

Checklist para Limpieza de Datos (Duplicados y Valores Nulos)

- [x] Cargar el archivo `dataframe/libros.csv` en un DataFrame utilizando `pandas`.
- [x] Identificar y eliminar filas duplicadas en los datos.
- [x] Analizar los valores nulos y decidir cómo manejarlos (rellenar, eliminar o marcar).
- [x] Documentar las filas eliminadas o modificadas, justificando cada decisión.

**Comment by medranopsycho** [comment]
Ya cargado el archivo utilice pandas e identifique que datos se pueden modificar, duplicar, mejorar o eliminar.

**Comment by medranopsycho** [comment]
ya esta realizado este issue
