### ISSUE TITLE
Formateo y normalización de datos 

### ISSUE THREAD

**Issue by Leosaucedo22** [DanaContreras17/ProyectoFinal951-2024-2#6]
Normalizar los campos de precios, autores y editoriales para asegurar consistencia (por ejemplo, convertir precios a un mismo formato).

- [x] Normalizar el campo de precios (asegurar un formato consistente)
- [x] Estandarizar los nombres de autores (corregir errores de formato o variaciones de nombres)
- [x] Estandarizar los nombres de editoriales (corregir inconsistencias o variaciones)
- [x] Revisar y ajustar otros campos si es necesario para asegurar consistencia
- [x] Guardar los datos limpios y normalizados en un archivo CSV llamado `libros_limpios.csv`
- [x] Confirmar que el archivo `datasets/libros_limpios.csv` esté listo para su uso en la base de datos

**Comment by medranopsycho** [comment]
Al revisar los datos me pude dar cuenta del campo de precios que se tenia que modificar y estandarice los nombres de los autores y editoriales

**Comment by medranopsycho** [comment]
ya están revisando los datos, no fue necesario modificar todos los datos ya que en su mayoría estaban limpios

**Comment by medranopsycho** [comment]
Una vez ya identificando los datos se modifico a un archivo nuevo que se llamo libros_limpios dentro de la carperta de datasets

**Comment by medranopsycho** [comment]
Ya esta el archivo csv con los "libros_limpios" para utilizarse
