### ISSUE TITLE
Diseño de la base de datos (diagrama)

### ISSUE THREAD

**Issue by Leosaucedo22** [DanaContreras17/ProyectoFinal951-2024-2#8]
Crear el diseño de las tablas necesarias para almacenar los datos de libros en MySQL.

- [x] Definir la estructura de la base de datos y el nombre de las tablas necesarias.
- [x] Crear la tablas con los campos adecuados.
- [x] Asegurarse de que cada campo tenga el tipo de dato correcto y restricciones necesarias (`id` como clave primaria)
- [x] Creación del Diccionario

**Comment by Yuls18** [comment]
Ya se realizó el diagrama en lucid, el diccionario lo hizó mi compañero Medrano.
